### PR TITLE
Insconfserv

### PR DESCRIPTION
**Pull request by TD-4242**
I want to open this pull request as a starting point for discussion.  It re-factors the file layout and a bit of the flow of the cookbook.  It follows a pattern that I found works well by having a dependency flow and gives options to install only, install + configure, or install + configure + start services.

Calling the default recipe will install, configure and start the services through the following dependency tree:

  default -> include_recipe 'service'
  service -> include_recipe 'configure'
  configure -> include_recipe 'install'

This gives the option of including dse::install or dse::configure in your run_list for dev/testing/validation.

What do you think of this?

### CODE REVIEW

**Comment by dcparker88** [comment]
I'll pull this down and work through it. I definitely like the idea of rearranging the flow, and is something I've want to do for a long time. I'll take a look at it and comment back here. thanks!

**Comment by TD-4242** [comment]
At this point there really isn't any code changes just some things moved around.

I think there has to be a better way to handle the templates.  I'm mulling some ideas around in my head that should allow attribute based changes in wrapper cookbooks for version upgrades rather than full changes/copys of the template erb files.  I will try to get some code out for review.

**Comment by dcparker88** [comment]
yeah - the thing I couldn't solve was the differences between templates for versions. For example, Cassandra 2.0 had a much different yaml than 1.2. There's probably a better way though. I'm interested in what you come up with.

**Comment by TD-4242** [comment]
yes, you did almost exactly what I did at my last position where I was creating all internal cookbooks.

**Comment by dcparker88** [comment]
Pulled this down and it looks good - merging this portion for and I am going to keep playing with it locally some, have some ideas

**Pull request merged**
