### PR TITLE
package intstallation timeout

### PR DESCRIPTION
**Pull request by blagoygenadiev-taulia**
package intstallation timeout - sometimes it needs to be adjusted as the default 900 seconds  might not be enouhg

### CODE REVIEW

**Comment by TD-4242** [comment]
Looks like foodcritic doesn't like the timeout.  Looks like a FC bug that may be fixed in a newer version.

Are you deploying a large number of cassandra nodes at the same time?  I've been doing 20-30 at a time in AWS and haven't hit a timeout.  I did refactor at one point to try to install each package individually prior to installing dse-full but it was only for ubuntu/debian packages.

Are you using a rhel based distro?  Doublecheck your chef run and see which package/packages it's failing on.  You may be able to do the same thing for rhel that I did for debian packages.

**Comment by blagoygenadiev-taulia** [comment]
Hi,

I am trying to build a docker container of centos 6.5 and dse-full inside. On my vagrant everything works fine but when I try building it via our Jenkins the chef run exits with "ERROR: yum -d0 -e0 -y install dse-full-4.8.0-1 exceeded timeout 900". 
I will check the chef run.

**Comment by TD-4242** [comment]
My guess is that it is due to all the dependencies of dse-full.  you may be able to copy the debian package installation loop.  The package names should be the same between debian and rhel.

I recommend something similar to this as it just moves the loop up to encompass the rhel distros:
```ruby
node['cassandra']['packages'].each do |install|
  case node['platform']
  # make sure not to overwrite any conf files on upgrade
  when 'ubuntu', 'debian'
    package install do
      version node['cassandra']['dse_version']
      timeout node['cassandra']['pkg-timeout']
      action :install
      options '-o Dpkg::Options::="--force-confold"'
    end
  when 'redhat', 'centos', 'fedora', 'scientific', 'amazon'
    package install do
      version node['cassandra']['dse_version']
      timeout node['cassandra']['pkg-timeout']
      action :install
    end
  end
end
```

Give that a try and see if it fixes it up for you.

**Comment by blagoygenadiev-taulia** [comment]
Yep, I took the dependency packages and looped their installation through.
Thanks fo rthe suggestion.

**Pull request closed without merging**
