### PR TITLE
Feature/5.0.4

### PR DESCRIPTION
**Pull request by tkrueger**
This adds the template files for version 5.0.4. 

A couple of the configuration files have changed. While the changes were mostly in indentation and documentation, I decided to add new copies of the files in question, so that they are as close to the originals as possible.

A side note: when testing these, I ran into trouble. What helped me was to update a couple of gems. Unfortunately, this has the side effect of testing with Chef version 12. I wasn't sure you wanted that, so I kept this out of this pull request. I have the changes in a different branch, if you're interested. The bottom line of this is that I'm not sure if the tests will run in the current setting.

### CODE REVIEW

**Comment by dcparker88** [comment]
pushed an update that I think will fix the travis builds. I would love to review what you have for tests in your other branch. once those tests start passing, this looks good 👍

**Comment by dcparker88** [comment]
scratch that, the update to travis didn't work. I would love to see what you did to get it working, even with chef 12

**Comment by tkrueger** [comment]
Sorry for taking so long, things happened.

Checked back into what I did for getting the tests running. For what it's worth, the current `master` branch does not run `rspec` tests on `master` successfully for me when I remove `Gemfile.lock` and do a `bundle install; bundle exec rspec`. It complains about cookbook `windows` being absent. I fixed that by adding it to the Berksfile. 

Without changes to the Gemfile, I then get this error for every test: `uninitialized constant Chef::Mixin::HomebrewUser`.  I'm on OSX.

After all that preamble, the changes that helped are at https://github.com/tkrueger/dse-cookbook/tree/feature/test-dependencies, the specific commit being 381a493.  I'll be happy to make that into a PR to discuss there.

**Comment by dcparker88** [comment]
@tkrueger the tests should be passing now. if you want to fix merge conflicts I can merge

**Pull request merged**
