### PR TITLE
Updated to 4.7.2.  Sync'd version suffixed templates from base 4.7.2 …

### PR DESCRIPTION
**Pull request by mdbelt**
…datastax packages (keeping chef attributes).

### CODE REVIEW

**Comment by mdbelt** [comment]
@dcparker88 - Danny, are you all interested in contributions from outside of Target, or is this a closed project?  Just planning how to handle the other changes I'm making for our organization in my fork.  Thanks.

**Comment by dcparker88** [comment]
hey, sorry. definitely interested in external contributions! I pulled this down to make sure it worked locally and totally forgot about it. It all looks good though, thanks :+1:

**Comment by mdbelt** [comment]
OK good deal.  I'll logically organize some of my changes & do some more PRs when I can.

**Comment by dcparker88** [comment]
awesome, thanks :)

**Pull request merged**
