### PR TITLE
added dse 4.8.1 cassandra.yaml file

### PR DESCRIPTION
**Pull request by calonso**

### CODE REVIEW

**Comment by calonso** [comment]
@dcparker88 I'd rather do a 'cassandra.yaml fallback system' as if we're requiring 4.8.1 and there's no such template 4.8.0 is used, but in order to keep ourselves moving this is good enough.

**Comment by dcparker88** [comment]
you can also chain templates, like https://github.com/target/dse-cookbook/blob/master/templates/default/cassandra_yaml/cassandra_4.6.6-1.yaml.erb

so if it doesn't change between minor versions you can tell it to just use the old one. I agree it's annoying to have to create that everytime, but that's where we are

**Comment by dcparker88** [comment]
lmk and I can either merge this or you can change the template behavior

**Comment by calonso** [comment]
@dcparker88 I prefer chaining than duplicating. Ready to merge now I think

**Comment by dcparker88** [comment]
perfect, :+1:

**Pull request merged**
