### PR TITLE
add templates for 4.7.0

### PR DESCRIPTION
**Pull request by dcparker88**

### CODE REVIEW

**Comment by TD-4242** [comment]
you need any help with the chefspec tests?

**Comment by dcparker88** [comment]
if you have a some time free, sure. I haven't had much of a chance to look, was getting ready to do that now.

**Comment by dcparker88** [comment]
@TD-4242 apparently the second package array was overwriting the first. Not sure why that happens..maybe that's a changed behavior in a newer version of chef.

**Comment by pmotch** [comment]
:+1:

**Comment by TD-4242** [comment]
interesting on the array merge.  Chefs handling of arrays has always been a bit unpredictable.

**Pull request merged**
