### PR TITLE
Config for DSE 4.6.6-1, and 4.8.0-1

### PR DESCRIPTION
**Pull request by gavinheavyside**
* Add templates for DSE 4.6.6-1 (just symlink to 4.6.2)
* Add templates for DSE 4.8.0-1, including new `compaction_large_partition_warning_threshold_mb` attribute
* Preserve opscenter config file when upgrading package with apt
* insert `dse-libspark` before `dse-full` in the package installation list

### CODE REVIEW

**Comment by gavinheavyside** [comment]
I haven't bumped the cookbook version in metadata.rb.

**Comment by dcparker88** [comment]
nice, thanks for this. can you fix the rubocop error?

**Comment by gavinheavyside** [comment]
Rubocop error resolved.

**Comment by dcparker88** [comment]
perfect, thanks!

**Pull request merged**
